### ISSUE TITLE
Hook-related breakage when upgrading to 7.2+

### ISSUE THREAD

**Issue by ronen** [react-dnd/react-dnd#1275]
**Describe the bug**
If I update from 7.1.0 to 7.2.0 or 7.3.1 -- but make no other changes, and no attempt to use hooks -- I get the following error in my previously-working app:

```
Internal Error (Unhandled Exception)

Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

at invariant ([--redacted--]/node_modules/react/cjs/react.development.js:88:15)
at resolveDispatcher ([--redacted--]/node_modules/react/cjs/react.development.js:1436:28)
at Object.useEffect ([--redacted--]/node_modules/react/cjs/react.development.js:1476:20)
at exports.DragDropContextProvider ([--redacted--]/node_modules/react-dnd/lib/cjs/DragDropContext.js:57:11) at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12892:18)
at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-
dom.development.js:14974:13)
at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15579:16)
at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-
dom.development.js:19266:12)
at workLoop (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19306:24)
at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:149:14)
```

**To Reproduce**
Unfortunately, I don't have a small test case to offer you.

**Expected behavior**
The app should work exactly as before :)

**Desktop (please complete the following information):**
 - MacOS 10.4
 - react 16.8.4
 - electron 4.1.0
 - electron-webpack 2.6.2
 - webpack 4.29.6

** Other notes **

For now I'm just pinning to 7.1.0 and all's good, since I'm not interested in the new features.  (I had just done a general `npm update` and saw the breakage, and tried rolling back to 7.20 and then 7.1.0 to get it working again.)

**Comment by darthtrevino** [comment]
Can I see how you're using DragDropContextProvider?

**Comment by ronen** [comment]
> Can I see how you're using DragDropContextProvider?

@darthtrevino man you're quick -- I didn't get a chance to get back to you on that, and you've already fixed it!  FYI I've tested my app against master and sure enough it's working.   Thanks for the speedy response.

**Comment by darthtrevino** [comment]
Well, it was more of a guess than anything - there was a hook invocation in one of our function components. But it's weird that it would blow up on you
