### ISSUE TITLE
export-namespace-from is not respected

### ISSUE THREAD

**Issue by kuldeepkeshwar** [react-dnd/react-dnd#1514]
**Describe the bug**
Seems like `export-namespace-from` is not respected when used with Next.js

```
/sandbox/node_modules/react-dnd/dist/esm/index.js:1
export * from './common';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.react-dnd (/sandbox/.next/server/static/development/pages/index.js:1298:18)
    at __webpack_require__ (/sandbox/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.js (/sandbox/.next/server/static/development/pages/index.js:1087:67)
    at __webpack_require__ (/sandbox/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (/sandbox/.next/server/static/development/pages/index.js:1132:18)
    at __webpack_require__ (/sandbox/.next/server/static/development/pages/index.js:23:31)
    at /sandbox/.next/server/static/development/pages/index.js:91:18
    at Object.<anonymous> (/sandbox/.next/server/static/development/pages/index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```
**Reproduction**

[Live Reproduction](https://codesandbox.io/s/test-nextjs-and-react-dnd-3wh28)

1. start any project with Next.js
2. install `react-dnd`
3. run the `yarn dev`

**Expected behavior**
It should get complied 

Although, the same works with CRA, [demo](https://codesandbox.io/s/test-react-dnd-ndmhu) here

**Comment by miguelpel** [comment]
Hi. I got a similar problem, I think;
`unexpected token error` when running tests with Jest in the create-react-app / Typescript environment.

<img width="1054" alt="Screenshot 2019-08-16 at 18 13 55" src="https://user-images.githubusercontent.com/26902621/63182422-d252be00-c052-11e9-95cc-5c97e9c11ce0.png">

**Comment by Oleksandr-kopaevich** [comment]
@kuldeepkeshwar, @miguelpel I had the same issue and maybe this can help you
similar discussion about module transpiling: https://spectrum.chat/next-js/general/have-no-idea-how-to-combine-amchart-with-next-js~37b6a631-663c-4a3c-94a0-568991f275de
the package itself: https://www.npmjs.com/package/next-transpile-modules

**but what described abode didn't helped me, so I did how described here and it works** 
https://github.com/react-dnd/react-dnd/issues/1414
and use these libraries:
https://www.npmjs.com/package/react-dnd-html5-backend-cjs
https://www.npmjs.com/package/react-dnd-cjs

**Comment by kuldeepkeshwar** [comment]
@Oleksandr-kopaevich thanks, that helped. Although it didn't require to use `cjs` library. I used the original `react-dnd`

**Comment by SunXinFei** [comment]
when I npm install will get the error ""

> @kuldeepkeshwar, @miguelpel I had the same issue and maybe this can help you
> Similar discussion about module transpiling: https://spectrum.chat/next-js/general/have-no-idea-how-to-combine-amchart-with-next-js~37b6a631-663c-4a3c-94a0-568991f275de
> the package itself: https://www.npmjs.com/package/next-transpile-modules
> 
> **But what described above hadn't helped me, so I did how described here and it worked**
> #1414
> and use these libraries:
> https://www.npmjs.com/package/react-dnd-html5-backend-cjs
> https://www.npmjs.com/package/react-dnd-cjs
===============
the version of react-dnd is 9.3.x;
when `npm install react-dnd`` npm install react-dnd-html5-backend` will get the error is "Unexpected token export ";
=>'`npm uninstall react-dnd`' & '`npm uninstall react-dnd-html5-backend` ' &
 '`npm install react-dnd-cjs`' '`npm install react-dnd-html5-backend-cjs`' 
and change the import :
```
import { DndProvider } from 'react-dnd-cjs'
import HTML5Backend from 'react-dnd-html5-backend-cjs'
```
will be ok;
thks

**Comment by sachinrajgire** [comment]
Installing cjs package worked for me .. I was using Next.js
