### ISSUE TITLE
Hook-related breakage when upgrade from 7.7.0 to 9.4.0

### ISSUE THREAD

**Issue by ronen** [react-dnd/react-dnd#1566]
**Describe the bug**
This appears to be the same problem that was fixed for #1275 

I upgraded my app from `react-dnd` 7.7.0 to `react-dnd-cjs` 9.4.0 and similarly for `react-dnd-html5-backend`   (Using `-cjs` to avoid figuring out how to get `electron-webpack & babel` to transpile `node_modules/react-dnd.*`)

The only change I made was to rename `DragDropContextProvider` to `DndProvider`.  Continuing to use the legacy wrapper API.

I'm getting this error:

```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.
This could happen for one of the following reasons: 
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks 
3. You might have more than one copy of React in the Same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

at /Users/ronen/[REDACTED]/node_modules/react/cjs/react.development.js:1607:26
at resolveDispatcher (/Users/ronen/adobe/audio/ lex/project-lex-frontend/node_modules/react/cjs/ react.development.js:1610:5)
at Object.useEffect (/Users/ronen/adobe/audio/lex/ project-lex-frontend/node_modules/react/cjs/ react.development.js:1648:20)
at /Users/ronen/[REDACTED]/node_modules/react-dnd-cjs/lib/common/DndProvider.js:36:11
at renderWithHooks (webpack-internal:///./ node_modules/react-dom/c]s/react-dom.development.js:16320:18)
at updateFunctionComponent (webpackinternal:///./node_modules/react-dom/cjs/reactdom.development.js:18284:20)
at updateSimpleMemoComponent (webpackinternal:///./node_modules/react-dom/cjs/reactdom.development.js:18222:10)
at updateMemoComponent (webpack-internal:///./ node_modules/react-dom/c]s/react-dom.development.js:18125:14)
at beginWork$1 (webpack-internal:///. / node_modules/react-dom/c]s/react-dom.development.js:20170:16)
at HTMLUnknownElement.callCallback (webpackinternal:///./node_modules/react-dom/cjs/reactdom.development.js:362:14)
```

As addressed by #1277, this seems to be due to a call to `Object.useEffect` 

**Reproduction**

Sorry, no small test case available

**Expected behavior**
App should work exactly as before :)

**Desktop (please complete the following information):**

MacOS 10.14.6
react 16.10.1
electron 6.0.11
electron-webpack 2.7.4
webpack 4.41.0

**Additional context**

For now I'm just sticking with ^7.7.0 and all's good, since I'm not interested in the new features. 
I just wanted to upgrade so that I wouldn't be 2 major versions out of date.

**Comment by omniphx** [comment]
Getting the same error in my `electron-webpack` project.

What's odd is that this works fine if webpack is already running (`electron-webpack dev`) and I install the `react-dnd-cjs` dependencies. However, after restarting webpack the error will occur.

My first guess was that a duplicate react instance was loading as described in Dan Abramov's article: https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375 ... but that doesn't appear to be the case:

![2019-11-17_14-17-06](https://user-images.githubusercontent.com/3722405/69012539-f620eb00-0944-11ea-998a-18dd227d5de0.png)

MacOS 10.14.6 
react 16.12.0
electron 5.0.7
electron-webpack 2.7.4
webpack 4.41.2

**Comment by omniphx** [comment]
Ended up solving this issue by adding externals to my `webpack.render.config.js` as mentioned here: https://github.com/facebook/react/issues/13991#issuecomment-521903787
```
module.exports = {
  externals: [
    'react',
    'react-dom'
  ],
```
Looks like the issue was due to duplicate react instances. Seems to be a common issue with `electron-webpack`

**Comment by andyengle** [comment]
@omniphx Thanks for sharing -- I too ran into this problem and your solution worked for me as well.

**Comment by rvetere** [comment]
Getting the same error in my `electron` app, powered with webpack... Super strange is, i'm developing almost the same app also as next.js web project, there it runs fine.

**Comment by ronen** [comment]
@darthtrevino - @omniphx's solution seems to work fine, though for #1277 you were able to fix the same issue without the need for that.    So I'm not sure if @omniphx's solution is a workaround or the final correct solution.   I'll leave it to you to close this issue as you see fit.

Thanks everyone

**Comment by omniphx** [comment]
@ronen I think this exposed more of an issue with my `electron-webpack` configuration rather than something wrong with `react-dnd`. For instance, before I defined externals I saw 3 copies of `react.development.js`:

![2019-11-17_12-31-06](https://user-images.githubusercontent.com/3722405/69439746-92683a80-0d15-11ea-9e08-ba02771c76f7.png)

The dnd library was probably referencing the by the react file that was local and my app was using the one served by webpack.

There's a small blurb about it on the github.io docs: https://react-dnd.github.io/react-dnd/docs/troubleshooting#make-sure-you-that-dont-have-duplicate-react

**Comment by jwallet** [comment]
can we remove the useEffect call inside `DndProvider` to be able to use it in an non-hook app?
