### ISSUE TITLE
拖拽的时候出现这个问题，官网demo也会有，是怎么回事啊

### ISSUE THREAD

**Issue by purpletastes** [react-dnd/react-dnd#1572]
browser.js:38 Uncaught Invariant Violation: Cannot call hover while not dragging.
    at invariant (https://c0esx.csb.app/node_modules/invariant/browser.js:38:15)
    at checkInvariants (https://c0esx.csb.app/node_modules/dnd-core/dist/esm/actions/dragDrop/hover.js:45:29)
    at DragDropManagerImpl.hover (https://c0esx.csb.app/node_modules/dnd-core/dist/esm/actions/dragDrop/hover.js:25:5)
    at Object.eval [as hover] (https://c0esx.csb.app/node_modules/dnd-core/dist/esm/DragDropManagerImpl.js:132:38)
    at HTML5Backend.handleTopDrop (https://c0esx.csb.app/node_modules/react-dnd-html5-backend/dist/esm/HTML5Backend.js:418:21)

**Comment by xiaoshuangLi** [comment]
最好还是自己先把问题定位一下，然后写个codesanbox 的 demo, 这样方便别人帮你解决问题，不然开发的人也是一头雾水。还有就是尽管现在都有谷歌翻译了，毕竟人家还是说英语的，尽量还是用英语把自己的问题描述一遍。
