### ISSUE TITLE
Example sortable list with hooks throws error

### ISSUE THREAD

**Issue by o-faro** [react-dnd/react-dnd#2967]
Great plugin, thanks for the work!

While researching I found a bug in the sortable list example.

**Steps to reproduce**
Go to https://react-dnd.github.io/react-dnd/examples/sortable/simple
Click on the button "Using Hooks" results in a blank page with this console error:

```
react-dom.production.min.js:209 Invariant Violation: Could not find the drag and drop manager in the context of DragSource(Component). Make sure to render a DndProvider component in your top-level component. Read more: http://react-dnd.github.io/react-dnd/docs/troubleshooting#could-not-find-the-drag-and-drop-manager-in-the-context
    at n (https://react-dnd.github.io/react-dnd/commons-b6fc23fdeae364952cfe.js:2:124289)
    at w.value (https://react-dnd.github.io/react-dnd/3fefa5a56057369feb2bef1627e48366c69a9ca9-9a1b8bfa91f074484bb7.js:2:914245)
    at https://react-dnd.github.io/react-dnd/3fefa5a56057369feb2bef1627e48366c69a9ca9-9a1b8bfa91f074484bb7.js:2:913861
    at vo (https://react-dnd.github.io/react-dnd/framework-d2701d15292b3c052111.js:2:119620)
    at cu (https://react-dnd.github.io/react-dnd/framework-d2701d15292b3c052111.js:2:108754)
    at ou (https://react-dnd.github.io/react-dnd/framework-d2701d15292b3c052111.js:2:108679)
    at Zo (https://react-dnd.github.io/react-dnd/framework-d2701d15292b3c052111.js:2:105709)
    at https://react-dnd.github.io/react-dnd/framework-d2701d15292b3c052111.js:2:57351
    at Fw0B.t.unstable_runWithPriority (https://react-dnd.github.io/react-dnd/framework-d2701d15292b3c052111.js:2:11158)
    at jl (https://react-dnd.github.io/react-dnd/framework-d2701d15292b3c052111.js:2:57060)
```
**Expected behavior**
See a working hooks example for sortable list with react-dnd 11.1.3

**Additional context**
I am using react-dnd on a large enterprise project in a sortable list and draging boxes in a grid, both built with hooks. The grid dnd is still working while the sortable list throws this already known error

```
Expected drag drop context
invariant
...
 25 |   );
  26 | } else {
  27 |   let argIndex = 0;
> 28 |   error = new Error(
     | ^  29 |     format.replace(/%s/g, function() {
  30 |       return args[argIndex++];
  31 |     })

```
I allready searched for this and none of the solutions were working for me. 
Do this two errors correlate? 

**Edit**
 Just saw that the typescript example uses Hooks and every example is throwing the reported error, when clicking the "Using Hooks" button. 
Would be nice if the "Expected drag and drop context" error would be explained in more detail

**Comment by o-faro** [comment]
The errors don't correlate.

May be this helps saving time for other people. 
After experimenting a lot I found a simple reason for my "Expected drag and drop context" error. 
The components in which `DndProvider` and the hooks `useDrag`, `useDrop` are declared must be located in the same file. 
I am working on a large application and split those up into differnet files, which was working in react 16.xx and broke after updating to react 17.xx
