### ISSUE TITLE
Getting "Uncaught Invariant Violation: Expected drag drop context" error despite the fact everything is wrapped in DndProvider

### ISSUE THREAD

**Issue by eden-lane** [react-dnd/react-dnd#3349]
I'm using react-dnd library in electron environment and getting this error.
My code:  

**index.tsx**:
```tsx
ReactDOM.render(
  <Providers>
    <App /> // <-- Here is code dependant on react-dnd
   </Providers>,
  document.querySelector('#root')
)
```

**Providers.tsx**:
```tsx
export const Providers = ({children}) => {
  return (
    <ApolloProvider client={apolloClient}>
      <DndProvider backend={HTML5Backend}>
        <NotificationsProvider>
          <AuthProvider source='app' token={token}>
            <GlobalStyle />
            <HotkeysProvider>
              <MemoryRouter>
                {children}
              </MemoryRouter>
            </HotkeysProvider>
          </AuthProvider>
        </NotificationsProvider>
      </DndProvider>
    </ApolloProvider>
  )
}
```

The error:
```
invariant.esm.js:29 Uncaught Invariant Violation: Expected drag drop context
    at invariant (http://localhost:8080/vendors.e8eae5d80de5ac0d48f8.js:362:15)
    at useDragDropManager (http://localhost:8080/vendors.e8eae5d80de5ac0d48f8.js:6797:66)
    at useDragSourceMonitor (http://localhost:8080/vendors.e8eae5d80de5ac0d48f8.js:6686:88)
    at useDrag (http://localhost:8080/vendors.e8eae5d80de5ac0d48f8.js:6590:92)
    at Task (http://localhost:8080/app.a3aeeb5d07bf07e82573.js:16234:68)
    at renderWithHooks (http://localhost:8080/vendors.e8eae5d80de5ac0d48f8.js:23119:18)
    at mountIndeterminateComponent (http://localhost:8080/vendors.e8eae5d80de5ac0d48f8.js:25945:13)
    at beginWork (http://localhost:8080/vendors.e8eae5d80de5ac0d48f8.js:27183:16)
    at HTMLUnknownElement.callCallback (http://localhost:8080/vendors.e8eae5d80de5ac0d48f8.js:12079:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8080/vendors.e8eae5d80de5ac0d48f8.js:12128:16)
```

**Comment by eden-lane** [comment]
I have a monorepo and apparently `useDrag` and `DndProvider` must be imported from the same place.
So I made following change to my webpack config:
```
resolve: {
  alias: {
    'react-dnd': path.resolve('../node_modules/react-dnd')
  }
},
```
