### ISSUE TITLE
Demo doesn't build?

### ISSUE THREAD

**Issue by theirishpenguin** [react-dnd/react-dnd#609]
I've followed the instructions in the Readme but when I run `npm start` I get...

```
$ npm start

> react-dnd@2.1.4 start /path/to/project/foo-react-dnd
> ./scripts/startSiteDevServer.sh

Hash: 8de6abe00282cfa22008
Version: webpack 1.14.0
Time: 11942ms
        Asset     Size  Chunks             Chunk Names
renderPath.js  2.88 MB       0  [emitted]  main
    + 520 hidden modules

ERROR in ./site/components/CodeBlock.js
Module not found: Error: Cannot resolve module 'react/lib/ReactUpdates' in /path/to/project/foo-react-dnd/site/components
 @ ./site/components/CodeBlock.js 19:28-61
[BABEL] Note: The code generator has deoptimised the styling of "/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js" as it exceeds the max of "100KB".
/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:3286
var browserInitScriptObj={__html:'window.INITIAL_PROPS = ' + JSON.stringify(this.props) + ';\n'};return _react2['default'].createElement('html',null,_react2['default'].createElement('head',null,_react2['default'].createElement('meta',{charSet:'utf-8'}),_react2['default'].createElement('title',null,'React DnD'),_react2['default'].createElement('meta',{name:'viewport',content:'width=device-width, initial-scale=1.0, maximum-scale=1.0'}),_react2['default'].createElement('link',{rel:'stylesheet',type:'text/css',href:this.props.files['main.css']}),_react2['default'].createElement('base',{target:'_blank'})),_react2['default'].createElement('body',null,this.state.renderPage && this.renderPage(),_react2['default'].createElement('script',{dangerouslySetInnerHTML:browserInitScriptObj}),_react2['default'].createElement('script',{src:this.props.files['main.js']})));};IndexPage.prototype.renderPage = function renderPage(){switch(this.props.loc

Error: Cannot find module "react/lib/ReactUpdates"
    at webpackMissingModule (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:19120:94)
    at Object.module.exports.exports.__esModule (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:19120:193)
    at __webpack_require__ (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:21:30)
    at Object.module.exports.exports.__esModule (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:6171:19)
    at __webpack_require__ (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:21:30)
    at Object.module.exports.exports.__esModule (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:19556:35)
    at __webpack_require__ (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:21:30)
    at Object.module.exports.exports.__esModule (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:18932:23)
    at __webpack_require__ (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:21:30)
    at Object.<anonymous> (/path/to/project/foo-react-dnd/__site_prerender__/renderPath.js:59:19)

npm ERR! Linux 3.13.0-95-generic
npm ERR! argv "/home/me/tools/node-4.4.5/bin/node" "/home/me/tools/node/bin/npm" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! react-dnd@2.1.4 start: `./scripts/startSiteDevServer.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-dnd@2.1.4 start script './scripts/startSiteDevServer.sh'.
npm ERR! This is most likely a problem with the react-dnd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/startSiteDevServer.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-dnd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-dnd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/project/foo-react-dnd/npm-debug.log
```

**Comment by theirishpenguin** [comment]
Okay, this will workaround this issue. Comment out `import ReactUpdates from 'react/lib/ReactUpdates` in site/components/CodeBlock.js. I'm not sure of the best way to cleanly fix this in the code. So I've no PR for this but here is the diff for the workaround...

```
diff --git a/site/components/CodeBlock.js b/site/components/CodeBlock.js
index ee9a5ca..667b1ab 100644
--- a/site/components/CodeBlock.js
+++ b/site/components/CodeBlock.js
@@ -1,6 +1,6 @@
 import React, { PropTypes, Component } from 'react';
 import { findDOMNode } from 'react-dom';
-import ReactUpdates from 'react/lib/ReactUpdates';
+//import ReactUpdates from 'react/lib/ReactUpdates';
 import StaticHTMLBlock from './StaticHTMLBlock';
 
 import './CodeBlock.less';
```
