### ISSUE TITLE
Testing with Enzyme: Expected sourceIds to be registered

### ISSUE THREAD

**Issue by ericpoon** [react-dnd/react-dnd#957]
Hey guys, 

I'm testing a component that is both a drag source and a drop target. But I got an error saying `Invariant Violation: Expected sourceIds to be registered.` when I ran this line `backend.simulateBeginDrag([sourceId])`. I have been Googling for a while but didn't figure out a solution, may someone help me a little bit please?

**Error trace**
```
    Invariant Violation: Expected sourceIds to be registered.

      59 | 
      60 |     console.log(sourceId, targetId);
    > 61 |     backend.simulateBeginDrag([sourceId]);
      62 |   });
      63 | 
      64 | });
      
      at invariant (node_modules/invariant/browser.js:40:15)
      at DragDropManager.beginDrag (node_modules/dnd-core/lib/actions/dragDrop.js:53:27)
      at Object.beginDrag (node_modules/dnd-core/lib/DragDropManager.js:92:33)
      at TestBackend.simulateBeginDrag (node_modules/dnd-core/lib/backends/createTestBackend.js:54:17)
      at Object.<anonymous> (src/tests/components/ImageBoard.test.js:61:13)
```

I can successfully log sourceId and targetId, which are S4 T7 respectively, but it just complained that it expected sourceIds to be registered.

**Component**
```javascript
import React from 'react';
import { DragDropContext } from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';
import SortableContainer from './SortableContainer';

const ROW_NUM = 3;
const COL_NUM = 3;

// todo: Item states are not persisted,
// use redux store to keep track of those images being edited (not all)

class ImageBoard extends React.Component {
  constructor(props) {
    super();
    this.state = { images: props.children };
  }

  componentWillReceiveProps(nextProps, nextContext) {
    this.setState({ images: nextProps.children });
  }

  moveCard = (dragIndex, hoverIndex) => {
    const { images } = this.state;
    const draggedCard = images[dragIndex];
    images.splice(dragIndex, 1, images[hoverIndex]);
    images.splice(hoverIndex, 1, draggedCard);
    this.setState({ images });
  };

  render() {
    const { images } = this.state;
    const { sortable } = this.props;
    const grid = [];

    images.forEach((current, index) => {
      const row = Math.floor(index / ROW_NUM);
      const col = index % COL_NUM;
      if (!grid[row]) grid[row] = [];
      grid[row][col] = sortable ? (
        <SortableContainer
          moveCard={this.moveCard}
          index={index}
          key={current.key}
        >
          {current}
        </SortableContainer>
      ) : current;
    });

    return (
      <div className={'image-card-collection'}>
        {grid.map(row => (
          <div className={'image-card-collection__row'} key={row.map(i => i.key).toString()}>
            {row.map(individual => individual)}
          </div>
        ))}
      </div>
    );
  }
}

export default DragDropContext(HTML5Backend)(ImageBoard);

```

**Test file**
```javascript
import React from 'react';
import { mount } from 'enzyme';
import TestBackend from 'react-dnd-test-backend';
import { DragDropContext } from 'react-dnd';
import ImageBoard from '../../components/ImageBoard';

const wrapInTestContext = (DecoratedComponent) => {
    return DragDropContext(TestBackend)(
      class TestContextContainer extends React.Component {
        render() {
          return <DecoratedComponent {...this.props} />;
        }
      }
    );
  };
  let wrapper, backend;
  beforeEach(() => {
    const Wrapped = wrapInTestContext(ImageBoard);
    wrapper = mount(
      <Wrapped sortable>
        <div key={1} />
        <div key={2} />
      </Wrapped>
    );
    backend = wrapper.instance().getManager().getBackend();
  });

  it('should work', () => {
    console.log(wrapper.debug());
    const dragSource = wrapper.find('DropTarget(DragSource(SortableContainer))').at(0).find('DragSource(SortableContainer)').instance();
    const dropTarget = wrapper.find('DropTarget(DragSource(SortableContainer))').at(1).instance();

    const sourceId = dragSource.getHandlerId();
    const targetId = dropTarget.getHandlerId();

    console.log(sourceId, targetId);
    backend.simulateBeginDrag([sourceId]);
  });
```

My environment: 
Yarn v1.3.2
NPM v5.5.1
Node v8.9.1

enzyme 3.3.0
react-dnd v2.5.4
react-dnd-test-backend v2.5.4

**Comment by ericpoon** [comment]
Okay, sorry I figured out that we should use an unconnected component: I was importing the connected ImageBoard
```javascript
export default DragDropContext(HTML5Backend)(ImageBoard)
```
But however, in test, we should actually use the unconnected version of ImageBoard (just ImageBoard itself without `DragDropContext(HTML5Backend)`)
Wrap the unconnected ImageBoard in test like this, so we can solve the issue
```javascript
wrapInTestContext(ImageBoard);
```
